name: Update YouTube Data (Production)

on:
  schedule:
    - cron: "0 14 * * *" 
  workflow_dispatch: 

jobs:
  update-data:
    runs-on: ubuntu-latest

    env:
      CRON_SECRET: ${{ secrets.CRON_SECRET }} 
      SITE_URL: "https://https://race2-learn.vercel.app/"

    steps:
      - name: Call production API
        run: |
          response=$(curl -s -w "%{http_code}" -X POST "$SITE_URL/api/youtube/update-database" \
            -H "Content-Type: application/json" \
            -d "{\"secret\": \"${CRON_SECRET}\"}")

          http_code="${response: -3}"
          body="${response%???}"

          echo "HTTP Status: $http_code"
          echo "Response: $body"

          if [ "$http_code" != "200" ]; then
            echo "❌ Update failed with status $http_code"
            exit 1
          else
            echo "✅ YouTube data updated successfully"
          fi
