name: Update YouTube Data
on:
    schedule:
        - cron: '0 6 * * *'  
    workflow_dispatch: 

jobs:
    update-data:
        runs-on: ubuntu-latest
        steps:
            - name: Update YouTube Database
              run: |
                  response=$(curl -s -w "%{http_code}" -X POST "${{ secrets.SITE_URL }}/api/youtube/update-database" \
                       -H "Content-Type: application/json" \
                       -d '{"secret": "${{ secrets.CRON_SECRET }}"}')
                  
                  http_code="${response: -3}"
                  body="${response%???}"
                  
                  echo "HTTP Status: $http_code"
                  echo "Response: $body"
                  
                  if [ "$http_code" != "200" ]; then
                      echo "❌ Update failed with status $http_code"
                      exit 1
                  else
                      echo "✅ YouTube data updated successfully"
                  fi